
    create table costs (
       id int8 generated by default as identity,
        sum numeric(19, 2),
        time timestamp,
        type int4,
        priority int4,
        reason varchar(255),
        wallet_id int8 not null,
        primary key (id)
    );

    create table incomes (
       id int8 generated by default as identity,
        sum numeric(19, 2),
        time timestamp,
        type int4,
        reason varchar(255),
        wallet_id int8 not null,
        primary key (id)
    );

    create table users (
       id int8 not null,
        name varchar(255),
        primary key (id)
    );

    create table wallets (
       user_id int8 not null,
        balance numeric(19, 2),
        primary key (user_id)
    );

    alter table if exists costs 
       add constraint FKp54e55wc2irl8x0d33wfpnsje 
       foreign key (wallet_id) 
       references wallets;

    alter table if exists incomes 
       add constraint FKcepqghg5b09u5crd6xpesv3kg 
       foreign key (wallet_id) 
       references wallets;

    alter table if exists wallets 
       add constraint FKc1foyisidw7wqqrkamafuwn4e 
       foreign key (user_id) 
       references users;

    create table costs (
       id int8 generated by default as identity,
        sum numeric(19, 2),
        time timestamp,
        type int4,
        priority int4,
        reason varchar(255),
        wallet_id int8 not null,
        primary key (id)
    );

    create table incomes (
       id int8 generated by default as identity,
        sum numeric(19, 2),
        time timestamp,
        type int4,
        reason varchar(255),
        wallet_id int8 not null,
        primary key (id)
    );

    create table users (
       id int8 not null,
        name varchar(255),
        primary key (id)
    );

    create table wallets (
       user_id int8 not null,
        balance numeric(19, 2),
        primary key (user_id)
    );

    alter table if exists costs 
       add constraint FKp54e55wc2irl8x0d33wfpnsje 
       foreign key (wallet_id) 
       references wallets;

    alter table if exists incomes 
       add constraint FKcepqghg5b09u5crd6xpesv3kg 
       foreign key (wallet_id) 
       references wallets;

    alter table if exists wallets 
       add constraint FKc1foyisidw7wqqrkamafuwn4e 
       foreign key (user_id) 
       references users;

    create table costs (
       id int8 generated by default as identity,
        sum numeric(19, 2),
        time timestamp,
        type int4,
        priority int4,
        reason varchar(255),
        wallet_id int8 not null,
        primary key (id)
    );

    create table incomes (
       id int8 generated by default as identity,
        sum numeric(19, 2),
        time timestamp,
        type int4,
        reason varchar(255),
        wallet_id int8 not null,
        primary key (id)
    );

    create table users (
       id int8 not null,
        name varchar(255),
        primary key (id)
    );

    create table wallets (
       user_id int8 not null,
        balance numeric(19, 2),
        primary key (user_id)
    );

    alter table if exists costs 
       add constraint FKp54e55wc2irl8x0d33wfpnsje 
       foreign key (wallet_id) 
       references wallets;

    alter table if exists incomes 
       add constraint FKcepqghg5b09u5crd6xpesv3kg 
       foreign key (wallet_id) 
       references wallets;

    alter table if exists wallets 
       add constraint FKc1foyisidw7wqqrkamafuwn4e 
       foreign key (user_id) 
       references users;

    create table costs (
       id int8 generated by default as identity,
        sum numeric(19, 2),
        time timestamp,
        type int4,
        priority int4,
        reason varchar(255),
        wallet_id int8 not null,
        primary key (id)
    );

    create table incomes (
       id int8 generated by default as identity,
        sum numeric(19, 2),
        time timestamp,
        type int4,
        reason varchar(255),
        wallet_id int8 not null,
        primary key (id)
    );

    create table users (
       id int8 not null,
        name varchar(255),
        primary key (id)
    );

    create table wallets (
       user_id int8 not null,
        balance numeric(19, 2),
        primary key (user_id)
    );

    alter table if exists costs 
       add constraint FKp54e55wc2irl8x0d33wfpnsje 
       foreign key (wallet_id) 
       references wallets;

    alter table if exists incomes 
       add constraint FKcepqghg5b09u5crd6xpesv3kg 
       foreign key (wallet_id) 
       references wallets;

    alter table if exists wallets 
       add constraint FKc1foyisidw7wqqrkamafuwn4e 
       foreign key (user_id) 
       references users;

    create table costs (
       id int8 generated by default as identity,
        sum numeric(19, 2),
        time timestamp,
        type int4,
        priority int4,
        reason varchar(255),
        wallet_id int8 not null,
        primary key (id)
    );

    create table incomes (
       id int8 generated by default as identity,
        sum numeric(19, 2),
        time timestamp,
        type int4,
        reason varchar(255),
        wallet_id int8 not null,
        primary key (id)
    );

    create table users (
       id int8 not null,
        name varchar(255),
        primary key (id)
    );

    create table wallets (
       user_id int8 not null,
        balance numeric(19, 2),
        primary key (user_id)
    );

    alter table if exists costs 
       add constraint FKp54e55wc2irl8x0d33wfpnsje 
       foreign key (wallet_id) 
       references wallets;

    alter table if exists incomes 
       add constraint FKcepqghg5b09u5crd6xpesv3kg 
       foreign key (wallet_id) 
       references wallets;

    alter table if exists wallets 
       add constraint FKc1foyisidw7wqqrkamafuwn4e 
       foreign key (user_id) 
       references users;
