package com.example.sunny_money_bot.enums;

public enum BotState {
    START,
    REGISTRATION,
    ENTER_NEW_INCOME,
    ENTER_SUM_OF_INCOME,
    ENTER_TYPE_OF_INCOME,
    ADD_NEW_REGULAR_INCOME,
    ENTER_INCOME_FREQUENCY,
    ENTER_INCOME_REASON,
    ADD_NEW_SINGLE_INCOME,
    ENTER_NEW_COSTS,
    ENTER_SUM_OF_COST,
    ENTER_TYPE_OF_COSTS,
    ADD_NEW_REGULAR_COST,
    ENTER_COSTS_FREQUENCY,

    ADD_NEW_SINGLE_COST,

    ENTER_PRIORITY_NEW_COST,
    ENTER_REASON_OF_COST,

    TRANSACTION_SAVED,
    GET_REPORT
}

